/// App-wide constants for FreeTier Radar.

class AppConstants {
  // Prevent instantiation
  AppConstants._();

  // API
  static const String defaultApiBaseUrl = 'https://freetier-radar-backend.onrender.com';
  static const Duration apiConnectTimeout = Duration(seconds: 15);
  static const Duration apiReceiveTimeout = Duration(seconds: 30);

  // Cache
  static const Duration cacheMaxAge = Duration(minutes: 30);
  static const String servicesCacheBox = 'services_cache';
  static const String alertsCacheBox = 'alerts_cache';
  static const String metaCacheBox = 'cache_meta';

  // SharedPreferences keys
  static const String prefApiBaseUrl = 'api_base_url';
  static const String prefThemeType = 'app_theme';
  static const String prefHasSeenOnboarding = 'has_seen_onboarding';
  static const String prefBookmarkedServices = 'bookmarked_services';
  static const String prefSavedStacks = 'saved_stacks';

  // Search
  static const Duration searchDebounce = Duration(milliseconds: 300);
  static const int maxSearchHistory = 10;

  // Pagination
  static const int defaultPageSize = 20;
  static const int maxPageSize = 100;

  // UI
  static const double cardBorderRadius = 12.0;
  static const double chipBorderRadius = 20.0;
  static const double modalBorderRadius = 20.0;
  static const double iconSizeSmall = 16.0;
  static const double iconSizeMedium = 24.0;
  static const double iconSizeLarge = 48.0;

  // Export
  static const String markdownHeader = '# 🚀 My Free Tier Tech Stack\n\n'
      '*Generated by [FreeTier Radar](https://github.com/freetier-radar)*\n\n';

  // Version
  static const String appVersion = '1.0.0';
  static const String appBuildNumber = '1';
}
