/// Markdown export utilities for FreeTier Radar.
///
/// Generates formatted markdown strings for sharing stacks,
/// individual services, and comparisons.

import '../models/service_model.dart';

class MarkdownExporter {
  // Prevent instantiation
  MarkdownExporter._();

  /// Generate markdown for a full tech stack.
  static String exportStack({
    ServiceItem? frontend,
    ServiceItem? database,
    ServiceItem? auth,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('# 🚀 My Free Tier Tech Stack\n');
    buffer.writeln('*Generated by FreeTier Radar*\n');

    if (frontend != null) {
      buffer.writeln(_serviceSection('☁️ Frontend', frontend));
    }
    if (database != null) {
      buffer.writeln(_serviceSection('🗄️ Database', database));
    }
    if (auth != null) {
      buffer.writeln(_serviceSection('🔐 Auth', auth));
    }

    // Summary
    final services = [frontend, database, auth].whereType<ServiceItem>();
    final needsCC = services.any((s) => s.requiresCreditCard);
    buffer.writeln('---\n');
    buffer.writeln(needsCC
        ? '⚠️ **Note:** Some services in this stack require a credit card.'
        : '✅ **Fully free stack** — no credit card required!');
    buffer.writeln('\n---\n');
    buffer.writeln('> Generated on ${DateTime.now().toIso8601String().split('T')[0]}');

    return buffer.toString();
  }

  /// Generate markdown for a single service.
  static String exportService(ServiceItem service) {
    final buffer = StringBuffer();
    buffer.writeln('## ${service.name}\n');
    buffer.writeln('**Category:** ${service.category.displayName}');
    buffer.writeln('**URL:** ${service.officialUrl}');
    buffer.writeln('**Free Tier:** `${service.freeTierLimits}`');
    buffer.writeln('**Credit Card Required:** ${service.requiresCreditCard ? "Yes" : "No"}');
    buffer.writeln('**Hard Cap:** ${service.hasHardCap ? "Yes (safe)" : "No (may overage)"}');
    buffer.writeln('**Status:** ${service.status.displayName}');
    if (service.changeLogSummary != null) {
      buffer.writeln('\n> ⚠️ ${service.changeLogSummary}');
    }
    buffer.writeln('');
    return buffer.toString();
  }

  /// Generate markdown for a list of bookmarked services.
  static String exportBookmarks(List<ServiceItem> services) {
    final buffer = StringBuffer();
    buffer.writeln('# ⭐ My Bookmarked Free Tier Services\n');
    buffer.writeln('*${services.length} services saved*\n');

    // Group by category
    final grouped = <ServiceCategory, List<ServiceItem>>{};
    for (final s in services) {
      grouped.putIfAbsent(s.category, () => []).add(s);
    }

    for (final entry in grouped.entries) {
      buffer.writeln('## ${entry.key.displayName}\n');
      for (final service in entry.value) {
        buffer.writeln('- **[${service.name}](${service.officialUrl})** — '
            '`${service.freeTierLimits}`'
            '${service.requiresCreditCard ? ' ⚠️ CC' : ' ✅ No CC'}');
      }
      buffer.writeln('');
    }

    buffer.writeln('---\n');
    buffer.writeln('> Generated by FreeTier Radar on '
        '${DateTime.now().toIso8601String().split('T')[0]}');

    return buffer.toString();
  }

  /// Generate markdown for a comparison table.
  static String exportComparison(List<ServiceItem> services) {
    if (services.isEmpty) return '';

    final buffer = StringBuffer();
    buffer.writeln('# ⚖️ Service Comparison\n');

    // Header row
    buffer.write('| Feature |');
    for (final s in services) {
      buffer.write(' ${s.name} |');
    }
    buffer.writeln('');

    // Separator
    buffer.write('|---------|');
    for (final _ in services) {
      buffer.write('---------|');
    }
    buffer.writeln('');

    // Rows
    buffer.write('| **Free Tier** |');
    for (final s in services) {
      buffer.write(' `${s.freeTierLimits}` |');
    }
    buffer.writeln('');

    buffer.write('| **Credit Card** |');
    for (final s in services) {
      buffer.write(' ${s.requiresCreditCard ? "⚠️ Required" : "✅ Not needed"} |');
    }
    buffer.writeln('');

    buffer.write('| **Hard Cap** |');
    for (final s in services) {
      buffer.write(' ${s.hasHardCap ? "✅ Yes" : "❌ No"} |');
    }
    buffer.writeln('');

    buffer.write('| **Status** |');
    for (final s in services) {
      buffer.write(' ${s.status.displayName} |');
    }
    buffer.writeln('');

    buffer.writeln('\n---\n');
    buffer.writeln('> Generated by FreeTier Radar');

    return buffer.toString();
  }

  static String _serviceSection(String label, ServiceItem service) {
    final buffer = StringBuffer();
    buffer.writeln('## $label: ${service.name}');
    buffer.writeln('- **URL**: ${service.officialUrl}');
    buffer.writeln('- **Free Tier**: `${service.freeTierLimits}`');
    buffer.writeln('- **Credit Card**: '
        '${service.requiresCreditCard ? "Required ⚠️" : "Not required ✅"}');
    if (service.status == ServiceStatus.CHANGED_RECENTLY) {
      buffer.writeln('- **⚠️ Note**: This service has been updated recently');
    }
    buffer.writeln('');
    return buffer.toString();
  }
}
